title: "Machine Learning Notes"
description: "My personal documentation for Machine Learning course"
theme: null
url: "https://sanjanb.github.io"
baseurl: "/Machine-Learning"

remote_theme: tomjoht/documentation-theme-jekyll

# Sidebar settings
sidebar:
  nav: sidebar
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
